# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  bedrock-trellis.local:
    site_hosts:
      - canonical: bedrock-trellis.local
        redirects:
          - www.bedrock-trellis.local
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@bedrock-trellis.local
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
